### ISSUE TITLE
Does it support Nvim?

### ISSUE THREAD

**Issue by boundless-forest** [jamescherti/vim-tomorrow-night-seablue#1]
I really like this theme a lot, but it seems it can only be used in vim.

**Comment by jamescherti** [comment]
Yes, the theme is compatible with Neovim. 

It can be installed with this one-liner:
```
mkdir -p ~/.config/nvim/colors &&  cd ~/.config/nvim/colors && curl -o tomorrow-night-deepblue.vim https://raw.githubusercontent.com/jamescherti/vim-tomorrow-night-deepblue/master/colors/tomorrow-night-deepblue.vim
```

**Comment by jamescherti** [comment]
Thank you for your appreciation! I'm glad you like the theme.

Yes, the theme is compatible with Neovim. 

The Tomorrow Night Deepblue colorscheme can be installed in Neovim with this one-liner:
```
mkdir -p ~/.config/nvim/colors &&  cd ~/.config/nvim/colors && curl -o tomorrow-night-deepblue.vim https://raw.githubusercontent.com/jamescherti/vim-tomorrow-night-deepblue/master/colors/tomorrow-night-deepblue.vim
```
